export { default as Header } from "./Header/Header"
export { default as HeroSection } from "./Main/HeroSection/HeroSection"
export { default as HeroNav } from "./Main/HeroSection/HeroNav"
export { default as AboutIcon } from "./Main/HeroSection/icons/AboutIcon"
export { default as ProjectIcon } from "./Main/HeroSection/icons/ProjectIcon"
export { default as ContactIcon } from "./Main/HeroSection/icons/ContactIcon"
