import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta http-equihttpEquiv="X-UA-Compatible" content="IE=7" />
        <meta http-equihttpEquiv="X-UA-Compatible" content="ie=edge" />
        <meta
          http-equihttpEquiv="Content-Type"
          content="text/html;charset=UTF-8"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="My Portfolio with Nextjs Generated by create next app"
        />
        <meta
          name="keywords"
          content="React, Nextjs, Portfolio, Headbwoi, Tochukwu, Full stack"
        />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>


      <main className="relative font-pop">
        <div className="text-3xl text-red-500">heyy</div>
      </main>

      <footer></footer>
    </>
  )
}

export default Home
