import type { NextPage } from "next"
import Head from "next/head"
import {
  HeroNav,
  HeroSection,
  AboutIcon,
  ProjectIcon,
  ContactIcon,
} from "../components"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta
          http-equihttpequiv="Content-Type"
          content="text/html;charset=UTF-8"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="My Portfolio with Nextjs Generated by create next app - Home Page"
        />
        <meta
          name="keywords"
          content="React, Nextjs, Portfolio, Headbwoi, Tochukwu, Full stack"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative font-pop bg-body overflow-x-hidden">
        <section className="hero relative h-adj w-full bg-[url('/bg-hero.png')] font-pop">
          <div className="container px-6 md:px-10 lg:px-5 xl:px-0 relative">
            {/* hero items' */}
            <HeroSection />
          </div>
        </section>
      </main>

      <footer className="relative">
        <div className="w-full h-20 md:h-24 absolute bottom-0 left-1/2 -translate-x-1/2 border border-cyan">
          <div className="flex items-center justify-center px-6 space-x-10 md:space-x-16 lg:space-x-20">
            {/* about */}
            <HeroNav name="about me">
              <AboutIcon />
            </HeroNav>
            {/* projects */}
            <HeroNav name="projects">
              <ProjectIcon />
            </HeroNav>
            {/* contact */}
            <HeroNav name="contact me">
              <ContactIcon />
            </HeroNav>
          </div>
        </div>
      </footer>
    </>
  )
}

export default Home
